### ISSUE TITLE
IPinfo DevRel with some tips

### ISSUE THREAD

**Issue by abdullahdevrel** [ExylumTechnical/ipinfo-report#1]
Thank you for using IPinfo's data for the project. We really appreciate your contribution to the open-source community.

I think you will enjoy using our [IPinfo CLI](https://github.com/ipinfo/cli) for your operations because it has a good amount of features built in that could be useful to you:

- Extract IP addresses from text using the `grepip` command
- Generate summary reports using the `summarize` command
- Bulk enrichment using the `bulk` command

https://github.com/ipinfo/cli

Also, we have the [summarize webpage](https://ipinfo.io/tools/summarize-ips) and [IPinfo map](https://ipinfo.io/tools/map) webpage that support up to 500k IP addresses.

**Comment by nicholas-howland** [comment]
Thank you for bringing this up Abdullah! I hope it is useful for environments where libraries cannot be imported easily or have limited memory space. I have used the ipinfo cli in the past in other projects and have found it has a lot more options and optimizations than my small project.
